import type { Metadata } from "next";
import "../globals.css"
import Menu from "../components/Menu";
import Link from "next/link";
import Image from "next/image";
import Navbar from "../components/Navbar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
  
      <div className="h-screen flex">
        {/* {left} */}
        <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] ">
        <div>
        <Link  className="flex items-center justify-center gap-2 lg:justify-start " href="/">
        <Image src="/logo.png" alt ="" width ={30} height={30}/>
        <span className="hidden lg:block font-semibold">School App</span>
        </Link>
        </div>
         <Menu/>
       </div>
       {/* {right} */}
        <div className="w-[86%] bg-[#F7F8FA] lg:w-[84%] xl:w-[86%] md:w-[92%] overflow-scroll flex flex-col">
         <Navbar/>
         {children}
        </div>
      </div>
     
  
  );
}
